project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "."
base_url: "https://api.crowdin.com"

preserve_hierarchy: true

files:
  - source: '/DockDoor/DockDoor/Localization/Localizable.xcstrings'
    translation: '/DockDoor/DockDoor/Localization/%locale%/Localizable.xcstrings'
    multilingual: 1