name: "Create Release"

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}
  cancel-in-progress: false

env:
  projname: DockDoor
  beta-channel-name: "beta"

jobs:
  preparation:
    name: Preparation job
    if: >-
      ${{ 
        github.event.issue.pull_request &&
        contains(github.event.comment.body, '/release') &&
        github.event.comment.user.login == 'YOUR_GITHUB_USERNAME' 
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Event Details
        run: |
          echo "Event Action: ${{ github.event.action }}"
          echo "Is PR: ${{ github.event.issue.pull_request }}"
          echo "Comment Body: ${{ github.event.comment.body }}"
          echo "Comment User: ${{ github.event.comment.user.login }}"
          echo "Repo Owner: ${{ github.repository.owner }}"
      - name: Add reactions
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: eyes
      - uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            if (pr.data.draft || pr.data.mergeable_state !== "clean") {
              core.setFailed("PR is not ready to be merged");
            }
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
        with:
          repo-token: ${{ secrets.REPO_TOKEN }}
      - uses: actions/checkout@v3
        if: success()
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          token: ${{ secrets.REPO_TOKEN }}
      - name: Set up Python and Install Dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r Configuration/requirements.txt
      - name: Extract latest changes
        id: latest_changes
        run: |
          source venv/bin/activate
          python3 ./Configuration/generate_latest_changes.py
      - name: Check if version already released
        run: |
          if [[ $(xcrun agvtool what-version -terse) == $(cat new_version) ]]; then
            echo "Version already released" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
      - name: Check if release notes are empty
        run: |
          if [[ -z $(cat latest_changes) ]]; then
            echo "Release notes are empty" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
      - name: Save generated info
        uses: actions/upload-artifact@v2
        with:
          name: generated-info
          path: |
            new_version
            title
            latest_changes
      - name: Save virtual environment
        uses: actions/upload-artifact@v2
        with:
          name: python-venv
          path: venv
      - name: Clean up generated files for sync
        run: |
          rm latest_changes
          rm title
          rm new_version
      - name: Sync branch
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ steps.comment-branch.outputs.base_ref }}
          target_branch: ${{ steps.comment-branch.outputs.head_ref }}
          github_token: ${{ secrets.REPO_TOKEN }}

  archive:
    name: Build and export app
    runs-on: macos-latest # Ensure we run on macOS to install the correct Xcode and Swift
    needs: preparation
    steps:
      - uses: actions/download-artifact@v2
        name: Download generated info
        with:
          name: generated-info
          path: artifacts
      - uses: actions/download-artifact@v2
        name: Download virtual environment
        with:
          name: python-venv
          path: python-venv
      - name: Parse info generated in preparation job
        id: info
        run: |
          echo "new_version=$(cat artifacts/new_version)" >> $GITHUB_OUTPUT
          echo "title=$(cat artifacts/title)" >> $GITHUB_OUTPUT
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
        with:
          repo-token: ${{ secrets.REPO_TOKEN }}
      - uses: actions/checkout@v3
        if: success()
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          token: ${{ secrets.REPO_TOKEN }}
      - name: Switch Xcode version
        run: |
          sudo xcode-select -s "/Applications/Xcode_15.3.app"
          /usr/bin/xcodebuild -version
      - name: Override versions in project
        run: |
          sed -i '' "s/_VERSION = $(xcrun agvtool what-version -terse)/_VERSION = ${{ steps.info.outputs.new_version }}/g" ${{ env.projname }}.xcodeproj/project.pbxproj;
      - name: Delete Package.resolved to fix dependency issues
        run: |
          rm -f ${{ env.projname }}.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
      - name: Resolve package dependencies
        run: |
          xcodebuild -resolvePackageDependencies -project ${{ env.projname }}.xcodeproj
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      - name: Build and archive
        run: xcodebuild clean archive -project ${{ env.projname }}.xcodeproj -scheme ${{ env.projname }} -archivePath ${{ env.projname }}
      - name: Export app
        run: xcodebuild -exportArchive -archivePath "${{ env.projname }}.xcarchive" -exportPath Release -exportOptionsPlist "Configuration/export_options.plist"
      - name: Zip app
        run: |
          cd Release
          ditto -c -k --sequesterRsrc --keepParent ${{ env.projname }}.app ${{ env.projname }}.zip
      - name: Upload archived app
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: Release/${{ env.projname }}.zip

  pre-release:
    name: Create pre-release
    runs-on: macos-latest
    environment: deploy-beta
    needs: archive
    if: ${{ contains(github.event.comment.body, 'beta') }}
    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
        with:
          repo-token: ${{ secrets.REPO_TOKEN }}
      - uses: actions/checkout@v3
        if: success()
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          token: ${{ secrets.REPO_TOKEN }}
      - uses: actions/download-artifact@v2
        name: Download generated info
        with:
          name: generated-info
          path: artifacts
      - uses: actions/download-artifact@v2
        name: Download virtual environment
        with:
          name: python-venv
          path: python-venv
      - uses: actions/download-artifact@v2
        name: Download archived app
        with:
          name: app
          path: Release
      - name: Activate virtual environment
        run: source python-venv/bin/activate
      - name: Parse info generated in preparation job
        id: info
        run: |
          echo "new_version=$(cat artifacts/new_version)" >> $GITHUB_OUTPUT
          echo "title=$(cat artifacts/title)" >> $GITHUB_OUTPUT
          mv artifacts/new_version new_version
          mv artifacts/title title
          mv artifacts/latest_changes latest_changes
      - name: Prepare Sparkle update creation
        env:
          PRIVATE_SPARKLE_KEY: ${{ secrets.PRIVATE_SPARKLE_KEY }}
        run: |
          echo -n "$PRIVATE_SPARKLE_KEY" > ./Configuration/sparkle_private_key
      - name: Generate Sparkle notes
        run: |
          source python-venv/bin/activate
          python3 ./Configuration/generate_html_for_sparkle_release.py
          mv Release/latest_changes.html Release/${{ env.projname }}.html
      - name: Update appcast
        run: |
          source python-venv/bin/activate
          ./Configuration/generate_appcast \
              --ed-key-file Configuration/sparkle_private_key \
              --link https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/releases \
              --download-url-prefix https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/releases/download/v${{ steps.info.outputs.new_version }}-beta/ \
              --channel ${{ env.beta-channel-name }} \
              -o docs/Support/appcast.xml \
              Release/
      - name: Save generated appcast
        uses: actions/upload-artifact@v2
        with:
          name: appcast
          path: docs/Support/appcast.xml
      - name: Create GitHub beta release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.info.outputs.new_version }}b - ${{ steps.info.outputs.title }}
          tag_name: v${{ steps.info.outputs.new_version }}-beta
          fail_on_unmatched_files: true
          body_path: latest_changes
          files: Release/${{ env.projname }}.zip
          prerelease: true
      - name: Create summary
        run: |
          echo "Beta Release v${{ steps.info.outputs.new_version }} created" > $GITHUB_STEP_SUMMARY
      - uses: actions/checkout@v3
        if: success()
      - name: Remove old appcast
        run: rm -rf docs/Support/appcast.xml
      - name: Retrieve previously generated appcast
        uses: actions/download-artifact@v2
        with:
          name: appcast
          path: docs/Support
      - name: Saving appcast
        uses: stefanzweifel/git-auto-commit-action@v4
        id: commit-appcast
        with:
          file_pattern: docs/Support/appcast.xml
          commit_message: "Update appcast with beta release for v${{ steps.info.outputs.new_version }}"

  release:
    name: "Create Release"
    runs-on: macos-latest
    environment: deploy-release
    needs: archive
    if: ${{ !contains(github.event.comment.body, 'beta') }}
    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
        with:
          repo-token: ${{ secrets.REPO_TOKEN }}
      - uses: actions/checkout@v3
        if: success()
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          token: ${{ secrets.REPO_TOKEN }}
      - uses: actions/download-artifact@v2
        name: Download generated info
        with:
          name: generated-info
          path: artifacts
      - uses: actions/download-artifact@v2
        name: Download virtual environment
        with:
          name: python-venv
          path: python-venv
      - uses: actions/download-artifact@v2
        name: Download archived app
        with:
          name: app
          path: Release
      - name: Activate virtual environment
        run: source python-venv/bin/activate
      - name: Parse info generated in preparation job
        id: info
        run: |
          echo "new_version=$(cat artifacts/new_version)" >> $GITHUB_OUTPUT
          echo "title=$(cat artifacts/title)" >> $GITHUB_OUTPUT
          mv artifacts/new_version new_version
          mv artifacts/title title
          mv artifacts/latest_changes latest_changes
      - name: Prepare Sparkle update creation
        env:
          PRIVATE_SPARKLE_KEY: ${{ secrets.PRIVATE_SPARKLE_KEY }}
        run: |
          echo -n "$PRIVATE_SPARKLE_KEY" > ./Configuration/sparkle_private_key
          rm -rf Release/*.app
          rm -rf Release/*.log
          rm -rf Release/*.plist
      - name: Generate Sparkle notes
        run: |
          source python-venv/bin/activate
          python3 ./Configuration/generate_html_for_sparkle_release.py
          mv Release/latest_changes.html Release/${{ env.projname }}.html
          python3 ./Configuration/remove_last_item_appcast.py
      - name: Update appcast
        run: |
          source python-venv/bin/activate
          ./Configuration/generate_appcast \
              --ed-key-file Configuration/sparkle_private_key \
              --link https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/releases \
              --download-url-prefix https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/releases/download/v${{ steps.info.outputs.new_version }}/ \
              -o docs/Support/appcast.xml \
              Release/
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.info.outputs.new_version }} - ${{ steps.info.outputs.title }}
          tag_name: v${{ steps.info.outputs.new_version }}
          fail_on_unmatched files: true
          body_path: latest_changes
          files: Release/${{ env.projname }}.zip
          prerelease: false
      - name: Saving changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: |
            docs/Support/appcast.xml
            ${{ env.projname }}.xcodeproj/project.pbxproj
          commit_message: "Update version to v${{ steps.info.outputs.new_version }}"
      - name: Create summary
        run: |
          echo "Release v${{ steps.info.outputs.new_version }} created." > $GITHUB_STEP_SUMMARY

  ending:
    name: Ending job
    if: always()
    runs-on: ubuntu-latest
    needs: [pre-release, release]
    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
        with:
          repo-token: ${{ secrets.REPO_TOKEN }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          token: ${{ secrets.REPO_TOKEN }}
      - name: Merge PR
        if: ${{ needs.archive.result == 'success' && needs.release.result == 'success'  && (needs.pre-release.result == 'success' || needs.pre-release.result == 'skipped') }}
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ steps.comment-branch.outputs.head_ref }}
          target_branch: ${{ steps.comment-branch.outputs.base_ref }}
          github_token: ${{ secrets.REPO_TOKEN }}
          message: "Release version v${{ steps.info.outputs.new_version }}"
      - uses: geekyeggo/delete-artifact@v2
        with:
          name: "*"
      - name: Add success reactions
        if: ${{ needs.archive.result == 'success' && needs.release.result == 'success'  && (needs.pre-release.result == 'success' || needs.pre-release.result == 'skipped') }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: rocket
      - name: Add negative reaction
        if: ${{ !(needs.archive.result == 'success' && needs.release.result == 'success'  && (needs.pre-release.result == 'success' || needs.pre-release.result == 'skipped')) }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: confused
