name: Update changelog on release published
on:
  release:
    types: [published]

jobs:
  changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Update changelog from release
        uses: rhysd/changelog-from-release/action@v3
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_summary_template: "chore: update changelog for %s"
          header: |
            <style>
                h1:first-of-type { display: none; }
                .my-5 { margin: unset !important; }
            </style>
            